version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.5-1
    environment:
    - DB_USER=gitlab
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    - DB_PASS=pass
    volumes:
    - pg:/var/lib/postgresql
  redis:
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - redis:/var/lib/redis
  gitlab:
    image: sameersbn/gitlab:8.11.7
    depends_on:
    - redis
    - postgresql
    ports:
    - 2222:22/tcp
    - 80:80
    hostname: gitlab.local
    environment:
    - GITLAB_PORT=80
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - DB_PASS=pass
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_NAME=gitlabhq_production
    - GITLAB_SECRETS_DB_KEY_BASE="1234"
    - GITLAB_SECRETS_SECRET_KEY_BASE="1234"
    - GITLAB_SECRETS_OTP_KEY_BASE="1234"
    - GITLAB_HOST=gitlab.local
    - GITLAB_SSH_PORT=2222
    volumes:
    - data:/home/git/data:Z
  registry:
    image: registry:2.4.1
    ports:
    - 5000:5000
    volumes:
    - registry:/registry
    environment:
    - REGISTRY_LOG_LEVEL=info
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
volumes:
  pg:
    external:
      name: policy2/postgresql
  redis:
    external:
      name: policy2/redis
  registry:
    external:
      name: policy2/registry
  data:
    external:
      name: policy2/data
